# Generated by scripts/bash2fish.py from dot_bash_alias. Do not edit by hand.

function reset --description 'bash alias: reset'
    cd $HOME; chezmoi apply; clear
end

abbr -a lg 'lazygit'
abbr -a vi 'nvim'
abbr -a vim 'nvim'
abbr -a svi 'sudo vi'
abbr -a ranger 'yazi'
abbr -a ping 'ping -c 5'
abbr -a fastping 'ping -c 100 -s.2'
abbr -a ls 'eza -al --color -h --group-directories-first'
abbr -a .. 'cd ..'
function ... --description 'bash alias: ...'
    cd .. && cd .. $argv
end

function .... --description 'bash alias: ....'
    cd .. && cd .. && cd .. $argv
end

function ..... --description 'bash alias: .....'
    cd .. && cd .. && cd .. && cd .. $argv
end

abbr -a rmdir 'rm -rfvI'
abbr -a rm 'rm -vI'
abbr -a du 'du -h'
abbr -a df 'df -h'
abbr -a less 'less -r -N'
abbr -a ports 'netstat -natp'
function countfiles --description 'bash alias: countfiles'
    find . -type f | wc -l $argv
end

abbr -a updatedb 'sudo updatedb --prunepaths=/mnt'
abbr -a updatewindb 'sudo updatedb'
abbr -a locate 'locate -ip'
abbr -a man 'man -a'
abbr -a ps 'ps -wef f'
abbr -a pgrep 'pgrep -af'
abbr -a sl 'ls -al --color -h --group-directories-first'
function ducks --description 'bash alias: ducks'
    du -cksh --threshold=1G * | sort -rn $argv
end

function duck --description 'bash alias: duck'
    bash -c 'for i in G M K; do    du -ah | grep [0-9]$i | sort -nr -k 1; done | head -n 11' $argv
end

abbr -a end 'less +G -N'
abbr -a podman 'podman-remote-static-linux_amd64'
abbr -a follow 'less +F -N'
function uppies --description 'bash alias: uppies'
    sudo apt update && sudo apt upgrade -y && sudo apt autoremove $argv
end

