# Generated by scripts/bash2fish.py from dot_bash_profile. Do not edit by hand.

set -gx EZA_CONFIG_DIR $HOME/.config/eza
set -gx EGET_BIN $HOME/.local/bin/
set -gx EGET_CONFIG $HOME/.config/eget/config.toml
set -gx EDITOR nvim
set -gx PAGER moar
set -gx REPO_ROOT $HOME/git/dotfiles
set -gx BIN_DIR $HOME/.local/bin
set -gx SSH_AUTH_SOCK $XDG_RUNTIME_DIR/openssh_agent
set -gx GITHUB_TOKEN ""

fish_add_path /opt/nvim-linux-x86_64/bin
fish_add_path $HOME/.cargo/bin
fish_add_path $HOME/go/bin
fish_add_path /usr/local/go/bin
fish_add_path /usr/local/bin
fish_add_path $HOME/.local/share/luals/bin
fish_add_path $HOME/.local/bin
fish_add_path /opt/nvim-linux64/bin
fish_add_path $HOME/.opencode/bin
