# Generated by scripts/bash2fish.py from dot_bash_profile. Do not edit by hand.

set -gx EZA_CONFIG_DIR $HOME/.config/eza
set -gx EGET_BIN $HOME/.local/bin/
set -gx EGET_CONFIG $HOME/.config/eget/config.toml
set -gx EDITOR nvim
set -gx PAGER moar
set -gx REPO_ROOT $HOME/.local/share/chezmoi
set -gx BIN_DIR $HOME/.local/bin
set -gx GITHUB_TOKEN ""

test -d /opt/nvim-linux-x86_64/bin; and fish_add_path /opt/nvim-linux-x86_64/bin
test -d /opt/nvim-linux64/bin; and fish_add_path /opt/nvim-linux64/bin
test -d $HOME/.cargo/bin; and fish_add_path $HOME/.cargo/bin
test -d $HOME/go/bin; and fish_add_path $HOME/go/bin
test -d /usr/local/go/bin; and fish_add_path /usr/local/go/bin
test -d /opt/homebrew/bin; and fish_add_path /opt/homebrew/bin
test -d /opt/homebrew/sbin; and fish_add_path /opt/homebrew/sbin
test -d /usr/local/bin; and fish_add_path /usr/local/bin
test -d /usr/local/sbin; and fish_add_path /usr/local/sbin
test -d $HOME/.local/bin; and fish_add_path $HOME/.local/bin
test -d $HOME/.local/share/luals/bin; and fish_add_path $HOME/.local/share/luals/bin
test -d $HOME/.opencode/bin; and fish_add_path $HOME/.opencode/bin
