#! /bin/bash

sources=(
    ~/.bash_functions
    ~/.bash_alias
    ~/.cargo/env
    /usr/share/bash-completion/bash_completion
    /etc/bash_completion
)

for source in "${sources[@]}"; do
    [ -f "$source" ] || continue
    . "$source"
done

case $- in
    *i*) ;;
      *) return;;
esac

HISTSIZE=100000
HISTFILESIZE=200000
HISTTIMEFORMAT="%d/%m/%y %T "
HISTCONTROL=ignoreboth

shopt -s histappend
shopt -s autocd
shopt -s cdspell
shopt -s dirspell
shopt -s checkwinsize

export PS1="\w\[\e[91m\]:󰣚\$\[\e[0m\] "
export EZA_CONFIG_DIR=~/.config/eza
export EGET_BIN=~/.local/bin/
export EGET_CONFIG=~/.config/eget/config.toml
export EDITOR=nvim
export PAGER=moar
export REPO_ROOT=~/git/dotfiles
export BIN_DIR=~/.local/bin
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/openssh_agent"
export GITHUB_TOKEN=

dirs=(
    /opt/nvim-linux64/bin
    ~/.local/bin
    ~/.local/share/luals/bin
    /usr/local/bin
    /usr/local/go/bin
    ~/go/bin
    ~/.cargo/bin
    /opt/nvim-linux-x86_64/bin
)

for d in "${dirs[@]}"; do
    [ -d "$d" ] || continue
    case ":$PATH:" in
        *":$d:") ;; # already present
        *) PATH="$PATH:$d";;
    esac
done

export PATH

fastfetch
ssh-add -l