#! /bin/bash

sources=(
    ~/.bash_functions
    ~/.bash_alias
    ~/.cargo/env
    /usr/share/bash-completion/bash_completion
    /etc/bash_completion
)

for source in "${sources[@]}"; do
    [ -f "$source" ] || continue
    . "$source"
done


case $- in
    *i*) ;;
      *) return;;
esac

export PS1="\w\[\e[91m\]:󰣚\$\[\e[0m\] "

fastfetch

# append to the history file, don't overwrite it
shopt -s histappend
HISTSIZE=100000
HISTFILESIZE=200000
HISTTIMEFORMAT="%d/%m/%y %T "
# don't put duplicate lines or lines starting with space in the history
HISTCONTROL=ignoreboth

shopt -s autocd
shopt -s cdspell
shopt -s dirspell
shopt -s checkwinsize

# Add a list of directories to PATH if they exist (idempotent)
export EZA_CONFIG_DIR=~/.config/eza
export EGET_BIN=~/.local/bin/
export EGET_CONFIG=~/.config/eget/config.toml
export EDITOR=nvim
export PAGER=moar
export REPO_ROOT=~/git/dotfiles
export BIN_DIR=~/.local/bin
export GITHUB_TOKEN=

# Append directories from an array to PATH if they exist (avoid duplicates)
dirs=(
    /opt/nvim-linux64/bin
    ~/.local/bin
    ~/.local/share/luals/bin
    /usr/local/bin
    /usr/local/go/bin
    ~/go/bin
    ~/.cargo/bin
    /opt/nvim-linux-x86_64/bin
)

for d in "${dirs[@]}"; do
    [ -d "$d" ] || continue
    case ":$PATH:" in
        *":$d:") ;; # already present
        *) PATH="$PATH:$d";;
    esac
done

export PATH

if [ -S $SSH_AUTH_SOCK ]; then
    eval $(ssh-agent) &> /dev/null && ssh-add ~/.ssh/*.priv &> /dev/null && ssh-add -l
fi