

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'b0o/tmux-autoreload'
set -g @plugin 'sainnhe/tmux-fzf'

set -g @open-lazygit 'G'
set -g @plugin 'AngryMorrocoy/tmux-neolazygit'

set -g @plugin 'noscript/tmux-mighty-scroll'
set -g mouse on

set -g @plugin 'jaclu/tmux-menus'
set -g @menus_trigger 'Space'

set -g @plugin '2kabhishek/tmux-tilit'
set -g @tilit-easymode 'on'
set -g @tilit-default 'even-vertical'


set -g @plugin 'alexwforsythe/tmux-which-key'

set -g @plugin 'ofirgall/tmux-window-name'
set -g @plugin 'tmux-plugins/tmux-resurrect'

#set -g @treemux-tree-client 'neo-tree-tree'
#set -g @treemux-tree-nvim-init-file '~/.tmux/plugins/treemux/configs/treemux_init.lua'
#set -g @plugin 'kiyoon/treemux'


set-option -g default-shell /usr/bin/fish

run '~/.tmux/plugins/tpm/tpm'
