#!/usr/bin/env python3
"""
Lightweight bash-to-fish converter. Reads dot_bash_profile, dot_bash_alias,
optionally dot_bash_functions; writes dotfiles.env.fish, dotfiles.abbr.fish,
and optionally function wrappers. No external repos. Run from repo root.
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path


def repo_root(script_dir: Path) -> Path:
    """Assume script lives in <repo>/scripts/."""
    return script_dir.parent


def parse_exports(profile_path: Path) -> list[tuple[str, str]]:
    """Extract export VAR=value from bash profile. Returns [(var, value), ...]."""
    exports: list[tuple[str, str]] = []
    text = profile_path.read_text()
    # export VAR=value or export VAR="value" or export VAR='value'
    for m in re.finditer(
        r"^\s*export\s+([A-Za-z_][A-Za-z0-9_]*)=(.*)$",
        text,
        re.MULTILINE,
    ):
        var, value = m.group(1), m.group(2).strip()
        value = value.strip("'\"").strip()
        # Expand ~ to $HOME for fish
        if value.startswith("~"):
            value = value.replace("~", "$HOME", 1)
        if value == "~/.config/eza":
            value = "$HOME/.config/eza"
        if "~" in value:
            value = value.replace("~", "$HOME")
        # Bash-only or set elsewhere for fish (ssh_agent.fish, starship).
        if var in ("PS1", "SSH_AUTH_SOCK"):
            continue
        exports.append((var, value))
    return exports


def parse_dirs(profile_path: Path) -> list[str]:
    """Extract dirs=( ... ) array from bash profile. Returns list of dirs in order."""
    text = profile_path.read_text()
    dirs: list[str] = []
    in_dirs = False
    for line in text.splitlines():
        if re.match(r"^\s*dirs\s*=\s*\(\s*$", line):
            in_dirs = True
            continue
        if in_dirs:
            if line.strip() == ")":
                break
            # Line like "    ~/.local/bin" or "    /usr/local/bin"
            m = re.match(r"^\s*(.+?)\s*$", line)
            if m:
                d = m.group(1).strip().rstrip("/")
                if d and not d.startswith("#"):
                    d = d.replace("~", "$HOME")
                    dirs.append(d)
    return dirs


def parse_aliases(alias_path: Path) -> list[tuple[str, str]]:
    """Parse alias key='value' or alias key="value" or alias key=value. Returns [(key, value), ...]."""
    aliases: list[tuple[str, str]] = []
    text = alias_path.read_text()
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        m = re.match(r"^\s*alias\s+([A-Za-z0-9_.-]+)=(.+)$", line)
        if not m:
            continue
        key, rest = m.group(1), m.group(2).strip()
        value = _extract_quoted(rest)
        if key and value is not None:
            aliases.append((key, value))
    return aliases


def _extract_quoted(rest: str) -> str | None:
    """Extract value from rest after '=': '...' or "..." or unquoted word."""
    if not rest:
        return None
    if rest.startswith("'"):
        i = 1
        while i < len(rest):
            if rest[i] == "\\" and i + 1 < len(rest):
                i += 2
                continue
            if rest[i] == "'":
                return rest[1:i].replace("\\'", "'")
            i += 1
        return rest[1:]
    if rest.startswith('"'):
        i = 1
        while i < len(rest):
            if rest[i] == "\\" and i + 1 < len(rest):
                i += 2
                continue
            if rest[i] == '"':
                return rest[1:i].replace('\\"', '"')
            i += 1
        return rest[1:]
    # Unquoted: take until space or end (alias vi=nvim)
    return rest.split()[0] if rest.split() else rest


def alias_needs_function(value: str) -> bool:
    """True if alias value contains &&, |, or $@ (use fish function instead of abbr)."""
    return "&&" in value or "|" in value or "$@" in value or ";" in value or " for " in value


def alias_use_bash_wrapper(value: str) -> bool:
    """True if alias value uses bash-only syntax (for/do/done/case/if/[[)."""
    return any(
        x in value for x in (" for ", " do ", " done ", " case ", " esac ", " if ", " fi ", " [[ ", " ]] ")
    )


def write_env_fish(out_path: Path, exports: list[tuple[str, str]], dirs: list[str]) -> None:
    """Write dotfiles.env.fish with set -gx and fish_add_path (reverse dir order)."""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by scripts/bash2fish.py from dot_bash_profile. Do not edit by hand.",
        "",
    ]
    for var, value in exports:
        if var == "GITHUB_TOKEN" and value == "":
            lines.append(f"set -gx {var} \"\"")
        else:
            lines.append(f"set -gx {var} {value}")
    lines.append("")
    # fish_add_path prepends; bash appends. So reverse dir order to get same effective order.
    for d in reversed(dirs):
        lines.append(f"test -d {d}; and fish_add_path {d}")
    out_path.write_text("\n".join(lines) + "\n")


def write_abbr_fish(out_path: Path, aliases: list[tuple[str, str]]) -> None:
    """Write dotfiles.abbr.fish with abbr or one-liner functions for complex aliases."""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by scripts/bash2fish.py from dot_bash_alias. Do not edit by hand.",
        "",
    ]
    for key, value in aliases:
        if alias_use_bash_wrapper(value):
            value_esc = value.replace("'", "'\"'\"'")
            lines.append(f"function {key} --description 'bash alias: {key}'")
            lines.append(f"    bash -c '{value_esc}' $argv")
            lines.append("end")
            lines.append("")
        elif alias_needs_function(value):
            if key == "reset":
                # No chezmoi apply (avoids install-deps hook); do not pass $argv to clear
                lines.append(f"function {key} --description 'bash alias: reset'")
                lines.append("    cd $HOME && clear")
                lines.append("end")
                lines.append("")
            else:
                value_esc = value.replace("'", "'\\''")
                lines.append(f"function {key} --description 'bash alias: {key}'")
                lines.append(f"    {value_esc} $argv")
                lines.append("end")
                lines.append("")
        else:
            value_esc = value.replace("'", "'\\''")
            lines.append(f"abbr -a {key} '{value_esc}'")
    out_path.write_text("\n".join(lines) + "\n")


def main() -> int:
    script_dir = Path(__file__).resolve().parent
    root = repo_root(script_dir)
    parser = argparse.ArgumentParser(description="Convert bash config to fish (lightweight)")
    parser.add_argument("--profile", type=Path, default=root / "dot_bash_profile", help="Bash profile path")
    parser.add_argument("--aliases", type=Path, default=root / "dot_bash_alias", help="Bash aliases path")
    parser.add_argument("--out-dir", type=Path, default=root / "dot_config" / "fish" / "conf.d", help="Output dir for .fish files")
    args = parser.parse_args()

    if not args.profile.exists():
        print(f"Profile not found: {args.profile}", file=sys.stderr)
        return 1
    if not args.aliases.exists():
        print(f"Aliases not found: {args.aliases}", file=sys.stderr)
        return 1

    exports = parse_exports(args.profile)
    dirs = parse_dirs(args.profile)
    aliases = parse_aliases(args.aliases)

    env_file = args.out_dir / "env.fish"
    abbr_file = args.out_dir / "alias.fish"

    write_env_fish(env_file, exports, dirs)
    write_abbr_fish(abbr_file, aliases)

    print(f"Wrote {env_file}")
    print(f"Wrote {abbr_file}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
